### ISSUE TITLE
General features

### ISSUE THREAD

**Issue by berserk82** [pereorga/minimalist-web-notepad#13]
Hello again. I wonder if this project does support the following features:
undo
redo
cut
copy
paste
save/export
new
close
open
zoom

Thanks in advance for either.

Bye, Ivano.

**Comment by pereorga** [comment]
Most of these features will work, depending in the browser used (it's a textarea). Did you try the demo?

**Comment by berserk82** [comment]
No, not yet. But I'll do ASAP.

**Comment by pereorga** [comment]
You'll see this app tries to be very minimal. Like Windows / Wine [Notepad](https://en.wikipedia.org/wiki/Microsoft_Notepad) or [Leafpad](http://tarot.freeshell.org/leafpad/) editor, but in the cloud.
It's just a few lines of code.
