### ISSUE TITLE
What about if 2 users write at the same time?

### ISSUE THREAD

**Issue by spartrekus** [pereorga/minimalist-web-notepad#16]
Hello,
I would be interested by having a collab editing possibility based on this excellent min editor.
Collaborative would be the goal.
I added a html refreshing of 1 min, on the page, but it does not help much.

Any idea how to make the PHP/Script work to write and see realtime what changes? (impossible maybe). 

Thank you and best regards

**Comment by pereorga** [comment]
It can be done, but it's a bit more complicated than the current file-based implementation. A first, easier step would be to stop overwriting the file, and then warn the user if another editor updated it first

**Comment by qex** [comment]
It really can be done, every client update send a location in extra. and server using fopen()/fseek()/fwrite() to handle file.

However that will not **minimalist** any more, I'd rather build a new project to build a collab version of this.

**Comment by pereorga** [comment]
I agree. A fork can be done for this if desired.
