### ISSUE TITLE
backslah in front of special character

### ISSUE THREAD

**Issue by woorzy** [pereorga/minimalist-web-notepad#2]
Hi Pere (Hola!),

I have a question about your nice script “Minimalist Web Notepad”.

Every time I wrote a special character like ‘ or “, and I leave the page, as soon I back the script it keep me add the backslash \ in front of this, so I found \’ or \”
Problem is every time I visit the page a new backslash is added, so I found in the end a page like \\\\\’ or \\\\\”

Where I can change the code to DO NOT ADD the backslash ?

**Comment by pereorga** [comment]
Closing this
