### ISSUE TITLE
Question - privacy policy/imprint feature

### ISSUE THREAD

**Issue by worldworm** [pereorga/minimalist-web-notepad#22]
Hi there,
since the gdpr or dsgvo I'am trying to place a privacy policy link on every webpage.
My private notepad installation is missing this option.

I'am thinking of adding 2 or 3 additional variables with url and text for that and place it in the footer.
Would it be ok if i open a pr when iam finished? Or wouldn't this fit in the minimalistic idea?

**Comment by pereorga** [comment]
Hi,

I see the reason behind this, but I would like to keep it minimal for now.

Thanks

**Comment by worldworm** [comment]
Thanks for your quick answer.
I can understand that well :)
