### ISSUE TITLE
Generate a random 8-char name instead of picking from a list

### ISSUE THREAD

**Issue by nodiscc** [pereorga/minimalist-web-notepad#3]
Hi, thanks for this nice app. I was looking for something similar to notepad.cc and this just does the job.

Is it possible to change the name generation procedure so that instead of picking a work in the words.txt list, the app generates a random 10-character alphanumeric name?

Once you figure out the server is running this app, it's trivial to get the list of words and enumerate notepad that have default names. I'd like to change that.

**Comment by pereorga** [comment]
This makes sense. I'm going to merge that if you submit a PR.
