### ISSUE TITLE
Ability to open files on server

### ISSUE THREAD

**Issue by ikwyl6** [pereorga/minimalist-web-notepad#33]
Can this be done via a menu with file listing of a particular directory on local webserver?

**Comment by pereorga** [comment]
It could be done, yes. I'm not interested in adding more complexity, though. Please consider forking the project if you want to add this feature.

**Comment by domOrielton** [comment]
I'm not 100% sure if my fork does what you need but it does show a file listing if enabled in the config (can be turned on/off as not everyone would want the notes to be visible in a list) - [https://github.com/domOrielton/minimal-web-notepad](https://github.com/domOrielton/minimal-web-notepad)

**Comment by ikwyl6** [comment]
I forked this project and added my own drop down menu with file listing. I need to update it to remote so it's reflected on github branch.
