### ISSUE TITLE
Can I add a real-time refresh function?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [pereorga/minimalist-web-notepad#37]
After editing, all devices can automatically refresh the page to display the content in real time. Is this feature open source added?

**Comment by domOrielton** [comment]
I don't think this would be easy to do and keep it minimal - you could use [Ratchet](http://socketo.me) or similar to add the functionality but this would move the project away from being minimalist. 

There is a NodeJS and Websockets implementation of a minimal notepad I've used before that has realtime updates - [https://github.com/petercunha/Pad](https://github.com/petercunha/Pad ) - that might fit your requirements, with the option to save the notes [here](https://github.com/petercunha/Pad/issues/3).

Hope this helps.

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
> I don't think this would be easy to do and keep it minimal - you could use [Ratchet](http://socketo.me) or similar to add the functionality but this would move the project away from being minimalist.
> 
> There is a NodeJS and Websockets implementation of a minimal notepad I've used before that has realtime updates - https://github.com/petercunha/Pad - that might fit your requirements, with the option to save the notes [here](https://github.com/petercunha/Pad/issues/3).
> 
> Hope this helps.

No No No !
Real-time refresh is the most basic function. It is like the water, electricity and coal you use every day. Without this function, it is difficult to have a perfect user experience, especially on a mobile phone screen with a smaller screen. Is it necessary to manually refresh the screen with F5? This is almost anti-human. Hahaha ~

**Comment by domOrielton** [comment]
This implementation is meant to be minimal - under 3kb last time I checked - and additional features are difficult to add without adding size and keeping it minimalist. If you can do it then I'm sure others would be grateful if you forked the project and added real-time refresh, would definitely be a useful addition.

**Comment by pereorga** [comment]
Closing this for now. Thanks!
