### ISSUE TITLE
The background color will become white in OBS dock.

### ISSUE THREAD

**Issue by iesvme** [pereorga/minimalist-web-notepad#47]
The background color will become white in OBS dock.
![image](https://user-images.githubusercontent.com/16969250/108951131-67039680-76a2-11eb-801c-c2dac62907c1.png)

**Comment by domOrielton** [comment]
OBS is Open Broadcaster Software (https://obsproject.com/)? Do you mean the text is white? From your screenshot that is how it looks to me in the Chrome browser with no text entered into the note - white background and gray border. When text is entered/loaded the text it black,

**Comment by iesvme** [comment]
Yes, obs is that. but how can I show the background color black in it as if
it opens in new edge browser? I love dark mode :)

domOrielton <notifications@github.com> 于 2021年3月3日周三 20:11写道：

**Comment by domOrielton** [comment]
As this will add to the code size I can't see this being added.  minimalist-web-notepad does work very well with browser extensions/add-ons like Dark Reader for Chrome/Firefox/Edge and that is probably the easiest way to do it. Or just add in your own custom code - something like this should be easy to add and should work - https://www.w3schools.com/howto/howto_js_toggle_dark_mode.asp
