### ISSUE TITLE
Live sharing?

### ISSUE THREAD

**Issue by wowcoo1** [pereorga/minimalist-web-notepad#49]
When typing in a client, all other clients with the web page opened should see the typing ASAP and w/o refreshing the page.

**Comment by domOrielton** [comment]
I believe this is covered in a previous closed issue -  [Can I add a real-time refresh function?](https://github.com/pereorga/minimalist-web-notepad/issues/37)

**Comment by baymax55** [comment]
> When typing in a client, all other clients with the web page opened should see the typing ASAP and w/o refreshing the page.

CodiMD is adapted for you

https://github.com/hackmdio/codimd
