### ISSUE TITLE
Issue with root URL

### ISSUE THREAD

**Issue by desult** [pereorga/minimalist-web-notepad#5]
Thanks for creating and sharing this! It's awesome! I found this while looking for a slimmed down version of notepad.cc; I like that there is no ability to add passwords.

My issue:
I would like to host this at desult.net/notes , but am having issues. The root URL for that website is my personal website dennisrothfuss.com because I have multiple domains on the same host. $URL = "http://desult.net/notes"; tries to find Root/desult/notes/index.php . I can, of course, make this change $URL = "http://dennisrothfuss.com/desult/notes" and it works , but I don't like the URL even though otherwise it is technically the same,

I've tried to hard code line 28 to read:
        header("Location: http://desult.net/".$name);
but It has the same issue.

I'm sorry to bug you about this because I do realize that there is so little code to look through to resolve the issue, but I'm stumped.

**Comment by pereorga** [comment]
Hi,

You should probably try something like:
$URL = $_SERVER['HTTP_HOST'] . '/notes';

**Comment by pereorga** [comment]
Let me know if it helps
