### ISSUE TITLE
can you add a function to add pictures

### ISSUE THREAD

**Issue by hiie** [pereorga/minimalist-web-notepad#50]
can you add a function to add pictures, that would be great

**Comment by domOrielton** [comment]
Knowing the code and pereorga's effort to keep it ultra minimalist, I think this is extremely unlikely to be done. It would require a big change in how the files/data is stored plus code to to upload the images/pictures. It would also raise questions of how the image is displayed - inline or as an attachment. If you want this functionality you would be better of using a rich text or markdown editor.

**Comment by hiie** [comment]
okay，thx
