### ISSUE TITLE
minimalist-web-notepad for Nextcloud

### ISSUE THREAD

**Issue by blackcrack** [pereorga/minimalist-web-notepad#51]
a app for nextcloud would cool,
2 parts,  

___*Cloud-Notepad*___
* one, 1st Part: the Navigations/Listing Panel (New Page Button+ Select img for ***<ShareGroups/ShareUsers/rename/delete>Page) 
* the 2nd Part: the listed/selected minimalist-web-Notepad as udf-8 <name("0new" to stand very up)>.txt in /minimalist-web-notepad  - hight/weight=100%
   (or how the User configuring in like [/office/mwnotepad ] in the Administration of the UserConfiguration of NC)

this gives short a possibility to put informations short by a Phonecall or other communicate via Talk in NC or other..
open short a new Web browser Nextcloud instance and open Cloud-Notepad by side.. with named Notepad Pages.

is more fast as "notes" and "short Notes" and per Page name is more selectable for Customer Names(todo/headlines/pagelines), User Names as headlines/rename able pagename and other Pagename(filename)/Headline ... 

best
Blacky

German Peoples of Nextcloud, because i write in german.. :  
@karlitschek @DeepDiver1975  
könnte ein schnelles ding sein um wärend nem Gespäch schnell was auf zu schreiben und danach dann um zu benennen, wie  
"Username Familienname,  
telefon vom 00.00.0000  
erledigen bis 00.00.0000 " (button hight=lines mit fester breite oder so, als dreizeiler oder mehr.. so sms ähnlich, 255 zeichen.. dateinamen eben..)  
oder "telefonnummer von Blabla" oder "wichtige Telefonnummern" die dann geteilt sind/wird mit User/s &/oder Gruppe "r" oder "rw" für andere..  oder anderes was in einem Textfile sein kann und minimal aufgeschrieben ist um es dann für andere zu teilen.. die es dann wisssen müssen, dabei könnte ja auch noch eine "neuerstellt notification" sein für user die das teil dann geteilt wird..  um zu wissen, daß da was iss..  wäre geil wenn solch ein minimalist-web-notepad in Nextcloud währe, könnte man schnell mal texte teilen, wie Ferieninfos, wichtige tage oder "Wichtige Telefonnummern" und dann eben minimalist-web-notepad als standart-lister-editor aus einem verzeichniss herraus, das dann die files darin listet &/oder shared. 
hab damit ein bisschen gespielt : [Beispiel](https://notes.orga.cat/whatever)  (Das Bildchen iss nich von mir)
liebe grüße
Blacky

**Comment by pereorga** [comment]
I'm not familiar with Nextcloud, and I am not sure if it would be useful, but I am happy if someone tries to integrate it, of course. But the aim of this repository is to be as simple as possible, so I'm not considering merging any application-specific code, not in the main branch at least.
