### ISSUE TITLE
how to post text to the url

### ISSUE THREAD

**Issue by shuivin** [pereorga/minimalist-web-notepad#53]
as title, i want to post some word by shell.

**Comment by worldworm** [comment]
Hey @shuivin 
try this:
`curl --data "text=this is the posted text" https://domain.ext/123`
Disclaimer: Does not work for the demo page (https://notes.orga.cat) due to cloudflare connection check

**Comment by shuivin** [comment]
Hey, @worldworm 

Thanks for your help.  it works!
