### ISSUE TITLE
xxx?raw can't be used in Nginx

### ISSUE THREAD

**Issue by nibazshab** [pereorga/minimalist-web-notepad#59]
Apache all is OK, but Nginx not.

```nginx
location / {
    rewrite ^/([a-zA-Z0-9_-]+)$ /index.php?note=$1$is_args$args;
}
```
Use `$is_args$args`, __url__ `xxx` and __argument__ `?raw` will become __url__ `xxx?raw`, it then be matched by  `!preg_match('/^[a-zA-Z0-9_-]+$/', $_GET['note'])` and be rewrited. So just need remove it.

```nginx
location / {
    rewrite ^/([a-zA-Z0-9_-]+)$ /index.php?note=$1;
}
```

I've already tested it.

So maybe https://github.com/pereorga/minimalist-web-notepad/commit/38459b4d713d4a18098ab669166239030851487d is not a good idea

**Comment by pereorga** [comment]
Thanks, I'll revert this then

**Comment by pereorga** [comment]
Reverted in https://github.com/pereorga/minimalist-web-notepad/commit/071d5b9fc9de9c62e29cf430f2acdcd7f216a998

**Comment by mouism** [comment]
```nginx
location ~* ^/notes/([a-zA-Z0-9_-]+)$ {
    try_files $uri /notes/index.php?note=$1;
}
````
当有目录时，目前的`nginx`的配置写法，参数 `?raw` 并不能会被传递。
也就是说，当访问 `/notes/test?raw` 是仅为 `/index.php?note=test`
而之前的写法，实际上会变为 `/index.php?note=test?raw` 
```nginx
location ~* ^/notes/([a-zA-Z0-9_-]+)$ {
    try_files $uri /notes/index.php?note=$1$is_args$args;
}
```
因为 `$is_args` 在有参数时，值为 `?`

因此实际能够传递参数的配置逻辑可能是这样的
```nginx
location ~* ^/notes/([a-zA-Z0-9_-]+)$ {
    set $args_append "";
    if ($is_args) { # if 块有问题 改为 map
        set $args_append "&$args"; 
    }
    try_files $uri /notes/index.php?note=$1$args_append; 
}
```
但是 `if` 块会有问题。If Is Evil

因此正确的方法是
