### ISSUE TITLE
password and encryption

### ISSUE THREAD

**Issue by muxinxy** [pereorga/minimalist-web-notepad#64]
Hope to have a password setting and encrypt data.

**Comment by pereorga** [comment]
Apparently this is a recurring request. This had been implemented in https://github.com/pereorga/minimalist-web-notepad/pull/43, and merged in the [encryption](https://github.com/pereorga/minimalist-web-notepad/tree/encryption) branch. 

We used to have a link in the README that pointed to that branch, but I removed it, as I don't plan to keep multiple branches up to date. And, as the plan for this project is to aim for maximum simplicity, I don't like to have encryption-related stuff merged in the main branch.

**Comment by Its4Nik** [comment]
> Hope to have a password setting and encrypt data.

@muxinxy 
You can just use nginx proxy manager

1. 
![image](https://github.com/user-attachments/assets/ec2f6011-960d-4a72-9219-999f3d3e8c9d)

2. 
![image](https://github.com/user-attachments/assets/b62e1c86-b61a-44a2-83b2-38c3b6160198)

3. 
![image](https://github.com/user-attachments/assets/4bebd7d1-2a9b-4a28-8efc-7af2392f4dfa)

You can leave "access" as it is

**Comment by muxinxy** [comment]
@Its4Nik Thanks for your answer!

**Comment by outt-iao** [comment]
可以修改php代码 让你设置的文件名 , 只读 任何人都不能修改 , 但是你可以直接修改程序目录下的_tmp文件的 
<?php

// Path to the directory to save the notes in, without trailing slash.
// Should be outside the document root, if possible.
$save_path = '_tmp';

// Disable caching.
header('Cache-Control: no-store');

// If no note name is provided, or if the name is too long, or if it contains invalid characters.
if (!isset($_GET['note']) || strlen($_GET['note']) > 64 || !preg_match('/^[a-zA-Z0-9_-]+$/', $_GET['note'])) {

    // Generate a name with 5 random unambiguous characters. Redirect to it.
    header("Location: " . substr(str_shuffle('234579abcdefghjkmnpqrstwxyz'), -5));
    die;
}

$path = $save_path . '/' . $_GET['note'];

// Define exact read-only file names
$read_only_files = array('1', 'secret', 'important');     //这里添加你想要的文件

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $text = isset($_POST['text']) ? $_POST['text'] : file_get_contents("php://input");
    
    // Check if file name is exactly in read-only list
    $file_name = basename($path);
    if (in_array($file_name, $read_only_files)) {
        header('HTTP/1.0 403 Forbidden');
        die('This file is read-only and cannot be modified.');
    }
    
    // Update file.
    file_put_contents($path, $text);

    // If provided input is empty, delete file.
    if (!strlen($text)) {
        unlink($path);
    }
    die;
}
