### ISSUE TITLE
Request - Realtime Editing or Write Lock

### ISSUE THREAD

**Issue by hilbrichtsoftware** [pereorga/minimalist-web-notepad#8]
Hello, 

I love this. Plain and simple as it should be. Do you think it would be possible to enable the show of realtime changes when multiple people edit at the same time?
Now I realize that is a lot of development work. So maybe instead put in a write-lock that indicates that somebody is writing. Or not even a real lock, just a warning message (less prone to trolling by leaving the edit window open and blocking everyone)

**Comment by pereorga** [comment]
Hi,

I like the idea of showing a warning and potentially locking the textarea when the data has changed. A client request every X seconds could perform that check.

A PR is welcome :+1:

**Comment by hilbrichtsoftware** [comment]
Sorry, I am not a PHP guy.

**Comment by pereorga** [comment]
No worries, but that was mostly client-side
